#!/bin/bash
COMMIT=$@
DEVDIR="~/Desktop/dev/MLua/LuaGRUB/LuaGRUB/"
STABLEDIR="~/Desktop/dev/MLua/LuaGRUB/LGRUB-stable/"
if ! [ $COMMIT ] ; then
  echo "You didn't include a commit description!"
  exit
fi
cd $DEVDIR
git add . -A
git commit -m "$COMMIT"
git push origin master
cd $STABLEDIR
git fetch upstream
git merge upstream/master
git push origin master
